FROM x9gg/image:base

USER root

ENV GO_VERSION=1.24.1

RUN wget -q https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz \
    && rm go${GO_VERSION}.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin
ENV GOPATH=/go
ENV PATH=$PATH:$GOPATH/bin
    
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" "$GOPATH/pkg"

RUN go version

USER dev
WORKDIR /home/dev

CMD ["zsh"]